### ISSUE TITLE
Define naming convention for smaller spacing increments

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris#113]
What naming convention should we use for smaller spacing increments?

Full word:
- `quarter`
- `half`

Decimals:
- `0.25`
- `0.5`

---

Originally brought up as a discussion point in a PR:
```suggestion
  '0.5x': tokens.spacing[0.5],
```
Interested to know peoples thoughts with decimals here. I like it 🤷

_Originally posted by @alex-page in https://github.com/Shopify/polaris/pull/102#discussion_r661864462_

**Comment by samrose3** [comment]
To the point about `33.3333`, we can also consider Tailwind's convention of fractions (ex: `1/2`, `1/3`, `2/5`, etc).

This also has the advantage for non-english and doesn't encounter the TypeScript scalar conversion problem (`width="1/3"` vs `width={0.33}` or `width={33%}`).

Just some sharing some observations. I'm not sure this applies here since spacing is different than sizing (sizing => width/height and spacing => padding/margin)

**Comment by kyledurand** [comment]
I like fractions as well @samrose3 I think they're more ergonomic than decimals / percentages

**Comment by alex-page** [comment]
Closing this as we have an opinion now. Thanks everyone!
