### ISSUE TITLE
Bring more flexibility to cards layout

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris#122]
Hi,

The card component has a nice 2/3 + 1/3 feature, but how can we easily create an easy grid of n components:

<img width="1047" alt="capture d ecran 2017-07-07 a 15 55 20" src="https://user-images.githubusercontent.com/1198915/27961008-9652750a-632d-11e7-9ca5-3477baec039a.png">

I've tried to played with Stack Item but I can't manage to achieve this.

Thanks :)

**Comment by alyseadlard** [comment]
Hey @bakura10! We use a similar kind of layout in a couple places in our main app, but it's not reused enough that we've made an official Polaris component. We know there's a strong need for it so we will be revisiting how we can add this in the future. 

For now it'll be best to create your own layout component since, like you've discovered, our Stack Item component doesn't support what you're wanting (for now).

**Comment by ry5n** [comment]
We’re looking at this again now, but we don’t have a firm timeline we can share. Until we do, Alyse’s advice is what we also do internally for our apps, and is a good way to go.
