### ISSUE TITLE
Tooltip content is under an HTML form field layer

### ISSUE THREAD

**Issue by Taphood** [Shopify/polaris#129]
# Issue Summary

Tooltip content shows under an HTML form field layer.

## Expected behavior

Tooltip content should show on the layer above any form field

## Actual behavior

Tooltip content shows under the layer of a form field
![tooltip-bug](https://user-images.githubusercontent.com/10623996/28179601-4d995804-67b7-11e7-89ca-33493afcf2fa.png)

## Expected behavior

Tooltip content should show the above layer of a form field
![tooltip-expected](https://user-images.githubusercontent.com/10623996/28179489-fa6829bc-67b6-11e7-9fb7-c1e3200eb4b5.png)

## Steps to Reproduce the Problem

1. Please use below code.
```jsx
<Stack
  vertical
  spacing="tight"
>
  <Tooltip
    content="This is a Tooltip content. This shows under the form field"
    preferredPosition="above"
  >
    <Link>
      <Stack 
         alignment="leading" 
         spacing="tight"
      >
      <p>{title}</p>
      <img 
        alt={`${title} description`}
        src={require("./../../../images/what.png")} 
        width="16" 
        height="16"
      />
      </Stack>
    </Link>
  </Tooltip>
  <TextField
     value={name}
     maxLength="20"
     placeholder="Prod select help"
     onChange={this.valueUpdater('name')}
     error={ myerror.name }
  />
</Stack>
```

## Specifications

-Polaris version: 1.1.1
-React version:15.5.4
-React DOM:15.5.4
-React Redux version:5.0.5
-React Router version: 4.1.1
-React Router DOM version: 4.1.1
-Browser: any
-Device: any
-Operating System: Mac OS 10.12.5

**Comment by ry5n** [comment]
@Taphood thanks for logging this. This looks like a bug with the Tooltip component specifically. I’ve logged this in our internal bug tracker and we’ll get this fixed for a future release.

There might be another solution in the meantime. It looks like you want to provide some in-context explanations on your form fields. Polaris has a solution for this: the `helpText` prop on TextField (and other form components). It’s great because it makes the help text immediately visible, and works great for touchscreen users too.

```jsx
<TextField
  label="Trigger timing"
  maxLength=20
  helpText="Short, helpful description of what trigger timing is"
/>
```
This has the advantage that the form field label (“Trigger timing”) is associated with the text field, ensuring your app is [accessible](https://polaris.shopify.com/principles/accessibility#usable-for-everyone) and follows best practices for good semantic HTML.

Let me know what you think of that option. In any case, I’ll leave this open until we get that stacking order resolved.

**Comment by lemonmade** [comment]
You can also check out https://github.com/Shopify/polaris/issues/107 for a solution to tooltip stacking issues. For now I will close this, though we will make the stacking behaviour better by default for the future.

**Comment by Taphood** [comment]
ry5n I've tried with helpText prop as ry5n suggested, but the below I see the help text shows always and with my validation error message, it looks too busy.  helpText prop seems nice feature btw, I will use it for somewhere it is applicable.

Here is the what I meant by too busy output for my case...
<img width="532" alt="screen shot 2017-07-15 at 10 25 07 am" src="https://user-images.githubusercontent.com/10623996/28241429-eb3a338e-6948-11e7-8af8-78c8c7213b0a.png">

I would like to show the help text when a user chooses to see by clicking on '?'

**Comment by Taphood** [comment]
Thanks lemonmade for your note on #107.  I've tried with z-index div but for some reason, I still couldn't get the tooltip content to be shown in a right position.  
yes, you can close this issue, since I decided to use ESDK Modal window instead.  I'm looking forward to seeing the stacking order default behavior enhancement in a future release

**Comment by ry5n** [comment]
@Taphood The help text is intended to be always visible to help merchants read it easily, even when the validation error is present. This is what we recommend: as long as both messages are helping the merchant, I wouldn’t worry about the interface looking busy.
