### ISSUE TITLE
Make textarea respect rows parameter

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris#133]
Hi !

I'd like to use the rows HTML attribute to make a textarea element taller by default. While the rows property is properly added to the HTML, it seems that Polaris restricts the default height to 36px. Would it be possible to adjust this value automatically so that height is 36px * number of rows?

Thanks!

**Comment by lemonmade** [comment]
Hey @bakura10, thanks for the issue. We actually do support this using the `multiline` prop on TextField. As you can see [here](https://github.com/Shopify/polaris-react/blob/master/src/components/TextField/TextField.tsx#L32), you can pass a number into that prop instead of a Boolean. When you do so, the field will be at least that many lines of text tall (or taller, depending on the content of the input).

Let me know if that doesn’t work for you.

**Comment by bakura10** [comment]
Hi,

This does not seem to work unfortunately. Here is my code:

```jsx
<TextField
                label="Description"
                value={this.state.trigger.description}
                id="description"
                maxLength="255"
                error={this.state.errors.description}
                helpText="You can write your own short description to provide more details about the trigger."
                multiline="3"
                onChange={this.updateField}
                onInput={this.validateField}
              />
```

No matter which value I use for multiline, it always appears with a fixed height of 36px by default:

<img width="618" alt="capture d ecran 2017-07-16 a 16 47 44" src="https://user-images.githubusercontent.com/1198915/28248542-86699b26-6a46-11e7-9cb0-754cb731e35c.png">

**Comment by bakura10** [comment]
Okay, got it. I actually need to use multiline={3} :). I'd say it's not really consistent as maxLength can support the number as a string :).

**Comment by lemonmade** [comment]
Good point that these are inconsistent. I'll add an issue to look at making them more consistent with one another.

**Comment by lemonmade** [comment]
Just as a follow-up, we decided that no changes were needed to the actual component here. Our typings show that both of these are meant to be numbers, `maxLength` only happens to work because we just pass it through to the input, whereas the `multiline` number is actually used. We are going to make some improvements to the style guide so that it better shows numbers in the playgrounds.

**Comment by ziaulrehman40** [comment]
Please mention this in docs somewhere, i had to google and find this issue to know this is possible. Thanks.
