### ISSUE TITLE
Use modal with complex content

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris#134]
Hi,

We have some modals whose content is a bit more complex than just a single text. However it seems that the Alert (or any modal) does not support custom content:

```jsx
<Alert ...>
            <p>Content 1</p>
            <p>Content 2</p>
          </Alert>
```

Is there a way to display that kind of content into modal?

**Comment by lemonmade** [comment]
Since we can’t correctly convert any components depending on JavaScript or CSS for presentation outside the app’s iframe, we restrict the Alert component to only take strings. Your only option for something like this is to create a separate endpoint in your app that you can load in using the [Modal component](https://polaris.shopify.com/components/embedded/modal#navigation).

**Comment by bakura10** [comment]
Thanks for the answer. That's definitely a big limitation for SPA :). Maybe this component should be re-used as a pure React component rather than relying on the Embedded SDK here?

**Comment by lemonmade** [comment]
Unfortunately there is just no way to do this in the context of an embedded app. We can’t render the modal in your iframe because it has to be able to extend outside the bounds of that iframe, and we can’t take arbitrary content and render it outside your iframe because of potential security issues.

**Comment by chaddjohnson** [comment]
What security issues does allowing such as `<p>` and `<strong>` impose? I can imagine a `<script>` tag being a potential security issue, but those and any other tags can be stripped out prior to content being rendered in the Alert body.

One use case is a warning alert. It would be helpful to have the ability to emphasize certain text in the alert to make the warning seem more severe.

**Comment by lemonmade** [comment]
Definitely understand the desire here. You can conceivably come up with a list of things that are safe but I doubt that there would be enough that we can do with this approach to make it good enough to be worth doing over the alternative (a modal that just loads a separate page). It is not merely `script` tags — many attributes could be used maliciously, as could things like images. We can't really execute any event listeners, which might be confusing and frustrating, it's unclear how links should work in content, etc.
