### ISSUE TITLE
Not receiving an event for onChange

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris#135]
# Issue summary

The documentation of text field (https://polaris.shopify.com/components/forms/text-field#navigation) indicates that the onChange event is supposed to received the new value and an event with all the details about the input.

However, what I'm receiving here is the value as first parameter, and the input ID as second parameter. There is no way to get the event.

I'd like rather to keep Polaris generating a unique ID for me and instead use the "name" (get from the event) to update our fields. As of today I've created a small function that prevents me to define callbacks for all fields:

```jsx
updateField = (value, id) => {
    this.setState({
      [id]: value
    });
  }
```

## Expected behavior

Instead I'd like to be able to do that:

```jsx
updateField = (value, event) => {
    this.setState({
      [event.target.name]: value
    });
  }
```

Is this a bug of the documentation or a misunderstanding from me ? :)

EDIT: apparently #83 said that this is the expected result, so I think the documentation is misleading ;).

**Comment by lemonmade** [comment]
Hey @bakura10, you're right that the docs are wrong, we'll get an update for this out soon. In general, avoiding the unique ID generation is good because it will be different between server and client (which is a performance issue when relying on server rendering). In general, you should be able to use the same `name` as `id`, and if not, you can typically have a pretty clear mapping between those two values.

**Comment by teodors** [comment]
I have a similar problem. Just checked the source and this is a big no, no. We have to be able to get the event data. 

```
@autobind
private handleChange(event: React.ChangeEvent<HTMLInputElement>) {
    const {onChange} = this.props;
    if (onChange == null) { return; }
    onChange(event.currentTarget.value, this.state.id);
}
```
Why not also pass the event?
```
onChange(event.currentTarget.value, this.state.id, event);
```

**Comment by celsowhite** [comment]
Because we can't access the event, I'm getting around this by doing the following.

Creating a method to handle input changes. In this method I can invoke other functions (that is the main reason I'm not inlining the setState into the input.

```javascript
handleInputChange(name, val) {
   this.setState({
      [name]: val
   });
}
```

Adding an onChange event on my inputs that passes the input value and my own custom name parameter.

```javascript
<TextField label="Image src" value={this.state.src} name="src" onChange={val => this.handleInputChange('src', val)} />
```

**Comment by sniepoort** [comment]
I find that lack of passing the event param pretty frustrating. Is there any logical reason why it's not included?

**Comment by sniepoort** [comment]
I realize that for your internal use, it is not a necessary feature. But since this package is also meant to be used by other developers, I still don't see an argument for not exposing the event. It could easily be passed as a third parameter, without any breaking changes. And seeing as several people have mentioned this as being useful (and in our case, essential), it would be great if you would consider implementing it.

**Comment by lemonmade** [comment]
Can you describe why it is essential for your use case?

**Comment by dylan** [comment]
In my case I want to use event.persist() like you can anywhere else in React. (see [here](https://reactjs.org/docs/events.html#event-pooling))

**Comment by lemonmade** [comment]
What do you want from the event that you need to persist? The persisted object isn’t really useful, there must be properties bar you are looking to grab that we don’t currently give you.

**Comment by dylan** [comment]
I was wrong in my case. Thank you for your response!

**Comment by ry5n** [comment]
Right now we’re happy with the current API, but if you’re still running into problems with this, please let us know.

**Comment by jejacks0n** [comment]
Ok, so I think I'm running into a similar problem, and the core of it seems to be the TypeScript `@autobind` decorator. I'm not familiar with TypeScript so I'm hoping @ry5n can reopen the issue and we can discuss it further.

My use case isn't about events. I'm only trying to provide custom behavior for `ResourceList.prototype.renderItem` ([as found here](https://github.com/Shopify/polaris/blob/master/src/components/ResourceList/ResourceList.tsx#L517)). My objective is to make a drag/drop sortable resource list, and so I need access to the `li` that's being rendered in that method, but there's literally no possibility of me ever being able to because of the way `@autobind` works.

That's where I think the problem lies honestly. It's defined as a "private" method, but if I inherit the class, I can't override it -- even though private dictates that subclass . and the primary reason is because somebody doesn't want to type`.bind(this)`.

This took me a good hour, hour and a half to debug, identify and confirm. I'm an experienced dev, and found this crazy frustrating. I struggle to think that this limitation is intentional and that the API is that no autobound method can be overridden in subclasses.

Unrelated, but similarly, you may want to declare some of these methods as protected and not private, based on how TypeScript seems to handle both for inheritance.

**Comment by jejacks0n** [comment]
By the way, it's been super nice using Polaris thus far. I just think this is a limitation that might not be fully understood.

**Comment by lemonmade** [comment]
@jejacks0n I think your issue is different enough to warrant a separate issue. In short, though: it is an intentional design decision, our use of private variables (and whatever decorators we choose to use on methods) is not meant to be anything a consumer would ever need to know, and subclassing React components is not a common pattern that we intend to support (at any time, we might switch to a function component, and it would not be a breaking change). Use cases that would require overriding methods are probably either indicative of a request for additional props, or an indication that the component in question probably isn’t right for the use case.

**Comment by jejacks0n** [comment]
That's reasonable and I appreciate the response @lemonmade. Follow up question before I create an issue. Does drag sorting of items within a ResourceList seem like I'm using the wrong component, or does it seem like we should try to expose the ability to do this via a PR or otherwise? It drives how I present the new issue and how much time I'm willing to invest in it.

Also, are Polaris components never inherited inside shopify's own usage of it? I feel like as a developer who understands inheritance, composition etc. that if the code is there and the pattern is there I can and should feel comfortable using it -- and in doing so, understand the risks and situation I choose to put myself and my project in. The usage of `@autobind` literally makes it a black box that I can't use and I'd still like to discuss the usage of `@autobind` vs. `.bind(this)` somewhere.

**Comment by jejacks0n** [comment]
The reality for me currently though -- given time constraints for a client project, is that I'm going to have to shim directly inside `index.js` and lock the version to enable what I'm looking for as we work to resolve it in a better way. That makes sad, hopefully understandably. =)

**Comment by lemonmade** [comment]
I would defer to @ry5n on whether dragging and dropping is a sensible thing to have within a ResourceList (I am going to guess that it has not been considered a core part of that component, given that we don't have UIs in our main product that does such a thing with lists of resources; the product picker on the collections page is probably the closest thing but it uses a different component internally). To answer your second question, no, in all of our codebase that has been migrated to React, we never inherit from any React component, from Polaris or elsewhere. In cases where we need behaviour not supported by inheritance, we've forked the component into a project, made the changes, and then either stuck with the fork (if it is was very unique) or committed those changes upstream into Polaris itself.

**Comment by ry5n** [comment]
ResourceList currently works well for listings that support these behaviors (number 1 is assumed for all resource lists, others are optional):

1. Browse and navigate by clicking an individual item
1. Filtering and sorting the list to find something specific
1. Multiple selection and bulk actions on the items

I considered drag-and-drop as a potential use case, but the component is complex enough that I don’t think I would use it for that, today. There’s just not enough in common between those behaviors and drag-and-drop.

I’m happy to chat about the specific interaction you’re working on, in a separate issue. Getting concrete about the UX problem often helps illuminate what components to use, whether to build anything new, and how to combine things.

**Comment by eballeste** [comment]
@thomasraydeniscool  i'm using formik with polaris, works fine...

```javascript

const CustomText = ({ field, form: { errors }, ...props }) => {
  if (errors[field.name]) {
    props.error = errors[field.name];
  }
  return (
    <TextField {...field} {...props} />
  );
};

<Formik
  initialValues={{ name: ''}}
  validationSchema={RuleGroupSchema}
>
  {({ setFieldValue }) => (
    ...
    <Field
      name="name"
      label="Name"
      component={CustomText}
      onChange={value => { setFieldValue('name', value) }}
    />
    ...
    <Button submit>Submit</Button>
  )}
</Formik>
```

**Comment by ChrisChiasson** [comment]
Without using the event, you can't save and restore the caret position if you transform the text in any way. For example when lower casing the input, if it happend to have a Capital letter beforehand, your caret will jump to the end of the input field. If we had access to the event, we could manipulate the caret position to keep it where it was before (perhaps somewhere in the middle). This is frustrating. Example: https://stackoverflow.com/a/49648061 (I'm going to try to find a workaround using capturing in an outer element vs. bubbling from the inner elements, but it should not be necessary)

**Comment by matthewhausman** [comment]
never used a UI library before where events aren't exposed (I have used many), anyone here may want to have access to the event for the reason that events exist in HTML / JS. 

For example, preventing default behavior is extremely common for handling phone number inputs. 

https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault
