### ISSUE TITLE
Providing on-boarding components

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris#136]
# Issue summary

Hi !

For apps it's often useful to provide an initial on-boarding screen to gather some information. Actually when you create a Shopify store you have a nice UX that looks like this:

<img width="1680" alt="capture d ecran 2017-06-27 a 15 18 48" src="https://user-images.githubusercontent.com/1198915/28315758-319e6902-6bc0-11e7-804d-40171e07221e.png">

## Expected behavior

I know it's a bit of an edge-case, but it would be super nice to be able to have such on boarding components right into Polaris :).

**Comment by ry5n** [comment]
It would be great to provide this! We’re actively take a look at what we want to recommend for onboarding merchants to your app and/or channel, which might be a bit different from what we do in Shopify admin. Until then, we’re not ready to release components.

On the plus side,  a lot of what you might need to build the contents of such a UI (form fields, buttons, Display text styles etc) is available in Polaris.

Since I don’t have a timeline for these components, I’m going to close this, but please let us know how it goes, and feel free to re-open if you have more questions.
