### ISSUE TITLE
Strange flickering on button when changing from normal to disable

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris#140]
# Issue summary

Hi,

First of all thanks a lot for Polaris. I've been finishing porting our app SMS Notifications (https://apps.shopify.com/sms-notifications) to Polaris, it looks georgous. Considering the very little CSS I've written, I couldn't be happier.

Here is however a visual glitch I've spotted.

## Expected behavior

When you switch from disabled button to non disabled, the background beautifully transition. However for the opposite (disabled => non disabled), it produces a strange glitch where it seems to go from violet to white then violet.

I would expect it to fade the same way.

As it's a bit hard to explain with text or image, I've made a short video exhibiting the issue: https://www.dropbox.com/s/9ny8d6fbsop3o6w/video.mov?dl=0

## Specifications

- Polaris version: 1.1

**Comment by ry5n** [comment]
Thanks for the props! I’m glad using Polaris has been a good experience. Thanks also for providing so much feedback. It’s really invaluable 🥇  

This button transition definitely doesn’t look great. I’ve logged an issue and we’ll get this fixed in a future release. Once it is fixed, I’ll close this issue.

**Comment by ry5n** [comment]
This is now fixed 🎉
