### ISSUE TITLE
Feature request: Datepicker - disabled dates list

### ISSUE THREAD

**Issue by sp4cecat** [Shopify/polaris#145]
# Issue summary

Add a **disabledDates** parameter for dates that should not be selectable.

## Expected behavior

You might want to have weekends or holidays disabled in the picker. An array of dates (or a callback that checks if a date is valid) is standard for most date pickers.

## Actual behavior

Currently, only **disabledDatesBefore** and **disableDatesAfter** parameters exist.

## Steps to Reproduce the Problem

N/A

## Specifications

- Polaris version: 1.1.1

**Comment by buggy** [comment]
I like the `disabledDate` parameter idea. It would be really nice if a `disabledDate` parameter could accept either an array of values or a function that returns an array of values. The function could be called with a `month` & `year` then return a list of values so that you don't need to know every possible date up front (for example: you could make an API call to a server to get the values for a specific month/year).

For the values of the array perhaps allow JavaScript Date() objects for specific dates and strings with weekday names? This would allow `["sunday", new Date("2017-12-25")]` so that you don't need to specify the date for every Sunday.

**Comment by ry5n** [comment]
Thanks for the request, @sp4cecat. This request makes a ton of sense. I’ve logged it in our backlog and made a note that it’s something we should definitely support.

I’d like us to tackle this soon, but until we have it in our committed workload, I’ll close this issue. That said, **I encourage everyone who wants this feature to add a 👍** to the original issue report. We’ll take the interest into account when we look at what to work on next.

💜
