### ISSUE TITLE
 Feature request: a table with "select all resources" feature

### ISSUE THREAD

**Issue by jimmyn** [Shopify/polaris#147]
# Issue summary

Is it possible to add a table with ***select all resources*** feature, that is widely used in Shopify. Or maybe there is a standard way, how this behaviour should be handled according to Polaris guidelines. 

![screen recording 2017-07-24 at 04 52 pm](https://user-images.githubusercontent.com/5391775/28526619-bc4998e0-7090-11e7-8ca3-7acbf7019a26.gif)

I'm facing this problem in multiple apps right now. I'm aware that you recommend to use `ResourceList` in most cases, but what about bulk actions?

**Comment by ry5n** [comment]
We’re working on V2 of ResourceList that will support bulk actions. I don’t have a firm timeline but our goal is to have this ready sooner rather than later.

In the meantime, you could make a new component based on [Resource.Item](https://github.com/Shopify/polaris/blob/master/src/components/ResourceList/Item.tsx) with the checkbox added. Then in ResourceList, you can render our items using your component instead of the built-in resource item, like so:

```jsx
```jsx
<ResourceList
  renderItem={(item, index) => {
    return <SelectableResourceItem key={index} {...item} />;
  }}
}
```

It will of course be a bit more complex to manage the selection and provide the ui for the bulk actions controls themselves, but it’s what I’d recommend, for now. Let me know if that helps.

**Comment by ry5n** [comment]
With version 2.0 of Polaris, [the resource list component](https://polaris.shopify.com/components/lists-and-tables/resource-list) now supports the UI for filtering, sorting and selecting with bulk actions 🎉 

We have quite a lot of docs on using the new component; don’s miss [the case study](https://polaris.shopify.com/components/lists-and-tables/resource-list#study) at the bottom of the page.
