### ISSUE TITLE
Add new exception status to ResourceList

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris#153]
# Issue summary

Hi,

The ResourceList is an awesome way to present data, especially the "exception" list. Currently, each exception item can support either three types: neutral, warning or critical.

I think it would be a great addition to add the blue "info" and the green "success".

In our use case, I'd like to showcase various information like when an email was open and read, and I think it would be great to be able to be able to show other kind of message there :).

**Comment by ry5n** [comment]
Interesting. The exceptions section of each resource item is intended to surface content that is specifically actionable. Meaning that it’s meant to bring merchants’ attention to unusual things about a particular item in a list, so that they can treat that item differently, if needed. That’s why the statuses are limited as they are.

Can tell me more about your use case(s)? I’d like to understand the design challenge better to see if expanding the available statuses makes sense.

**Comment by bakura10** [comment]
Hi,

Sure. Actually we want to display a list of emails sent, and display some info, like when it converted and how much it converted (we are using the new marketing events API to do that). So I wanted to display a text like "This email helped you generate xx€".

But at the end I've actually decided to instead use a simpler tag "Converted" and display the data in the details.

**Comment by ry5n** [comment]
OK, yes, I think that’s a better solution from a design point of view. Let me know if you have any other questions about it.
