### ISSUE TITLE
Question: libraries for data visualization?

### ISSUE THREAD

**Issue by JoshHighland** [Shopify/polaris#154]
# Issue summary

Maybe I'm missing something. Where are the data visualization components for us to use? The Polaris guidelines are great but fall short in providing information as to what libraries are recommended as they are not provided in the Polaris source (https://polaris.shopify.com/visuals/data-visualizations)

## Expected behavior
More details on how to generate these charts or access to the libraries Shopify uses to generate their own.

## Actual behavior
No information on how to generate these charts.

**Comment by ry5n** [comment]
Hi @JoshHighland. Right now we don’t have dataviz components that are ready for release as part of Polaris. It’s definitely on our radar, and your interest helps us set priorities. Right now we’re building internally using [Highcharts](https://www.highcharts.com/demo) and have worked with [D3](https://d3js.org/) as well. D3 is pretty low-level and requires more investment; Highcharts is quicker to get going but has more constraints on what you can achieve. Neither is particularly “React-y”.

Since it’s early days and I don’t have a release timeline, I’m going to close this. But please do continue to provide feedback, and feel free to share your experience implementing the dataviz design guidelines.

**Comment by cgenevier** [comment]
I'm definitely interested in this too. In the absence of Shopify's own data visualization libraries, I'm currently using [Recharts](http://recharts.org/#/en-US) which so far is pretty decent.
