### ISSUE TITLE
How can we customize the colors, font-sizes, borders, etc?

### ISSUE THREAD

**Issue by anaibol** [Shopify/polaris#164]

**Comment by dfmcphee** [comment]
Hi @anaibol, thanks for reaching out. We don't allow for changing things like colors and font-sizes because the aim for Polaris is to make those things consistent between Shopify and the apps using it. It isn't intended to be used as a framework like bootstrap, where it is completely customizable. It is instead an opinionated system for how we think Shopify should be built.

**Comment by anaibol** [comment]
Ok so it's only built for shopify plugins?

**Comment by dfmcphee** [comment]
Yep, exactly. It is designed for building interface within Shopify and apps for Shopify.
