### ISSUE TITLE
How to make a table like Crush.pics?

### ISSUE THREAD

**Issue by AdityaAnand1** [Shopify/polaris#182]
From [this](https://www.shopify.com/partners/blog/how-to-get-your-app-featured-on-the-shopify-app-store?utm_medium=social&utm_campaign=partnersocial&utm_source=facebook&utm_content=resource) shopify blog post, I saw that the crush.pics app is somehow creating a very well formatted table and they're using the embedded sdk. 

My question is, is the following possible with just polaris or do we have to write custom components/css for this? ResourceList doesn't seem to support this kinda weighting and anchoring and alignment.

![image](https://cdn.shopify.com/s/files/1/0533/2089/files/get-your-app-featured-ui-with-embedded-sdk.png?v=1485201045)

**Comment by dfmcphee** [comment]
Hey @AdityaAnand1, thanks for reaching out. We don't have a table quite like that, but we do have the [resource list component](https://polaris.shopify.com/components/lists/resource-list#section-examples).

We decide to make things like this lists instead of tables because it makes more sense semantically (it isn't tabular data) and it scales better to small screens.

The resource list allows you to pass attributes to each item as well as badges (similar to the ones in your example).
