### ISSUE TITLE
[Tabs] Change API to use `content` instead of `title`

### ISSUE THREAD

**Issue by dfmcphee** [Shopify/polaris#229]
To be consistent with the wording of our other component APIs, we should rename the tab descriptor prop to `content` instead of `title`.

**Comment by buggy** [comment]
@dfmcphee Can I suggest switching to `content` in the 1.10 release and making `title` a synonym for it? If someone uses `title` instead of `content` then log a warning to the console that `title` is now deprecated/will be removed in 2.0 and they need to use `content` instead. This maintains backwards compatibility while helping developers upgrade their apps in preparation for 2.0.

**Comment by dfmcphee** [comment]
That is a great suggestion @buggy. I will see if we can get that alias into the 1.9 release.

**Comment by dfmcphee** [comment]
Merged into the 2.0 beta.
