### ISSUE TITLE
Theres no documentation for "Segment" component

### ISSUE THREAD

**Issue by IvanLinos** [Shopify/polaris#242]
Radiobuttons seems to lack of a option to make them visually "Toggable Buttons" like these:

![toggle](https://user-images.githubusercontent.com/23552631/33940878-fffce9d0-e010-11e7-89d1-3594b5d8e602.png)

![sketch](https://user-images.githubusercontent.com/23552631/33940963-55203494-e011-11e7-9f59-81f91ff785e0.png)

Not only Polaris documentation but also the Sketch UI files are full of graphic examples of this, but... how can we add them into our apps???

**Comment by dfmcphee** [comment]
This is a variation on our `ButtonGroup` component. You can see the example here: https://polaris.shopify.com/components/actions/button-group

**Comment by IvanLinos** [comment]
Hi @dfmcphee, yes that was the closer component to the functionality im looking for, but there is no reference for the "pushed" button of the group. Doest that feature exists or its just not documented? I searched for the source of the button group component but didnt find anything.

Thanks & Regards.

**Comment by dfmcphee** [comment]
Ah, yes. Currently there is no way to manually set that "pressed" state to use like a toggle. That is only set through the actual `:active` state of the button when clicked.

**Comment by ry5n** [comment]
This is something we’d like to add to Polaris, but it’s not on the immediate todo list. We’d probably implemented this as a new component, since it functions as a set of radios rather than being a simple group of independent buttons. If you still need this I’d recommend building a similar component in your project, using `ChoiceList` and `ButtonGroup` as reference.

To avoid further confusion, I’ve made a note to remove the version you see in the Sketch UI kit until we have it implemented.

**Comment by panzi** [comment]
Is there something for this now available?
