### ISSUE TITLE
Feature Request: Pricing Table for Apps

### ISSUE THREAD

**Issue by buggy** [Shopify/polaris#259]
# Issue summary

Many apps in the app store use plans and allow customers to choose their plan using a pricing table but there is no pricing table component or example of how to build a responsive pricing table using Polaris.

## Expected behavior

Either a Pricing Table component or an example of how to construct a pricing table using existing Polaris components.

## Actual behavior

Really ugly non-standard solutions

## Steps to reproduce the problem

N/A

## Specifications

- Polaris version: 1.10
- React version: any
- Browser: any
- Device: any
- Operating System: any

**Comment by chloerice** [comment]
Hey @buggy, I'm not quite clear on exactly what kind of table you're referring to. Can you add a screenshot to your issue description? That will help clear up whether a resource list or a data table would be a useful solution for you (resource list is totally revamped--preview in the current beta--and data table is finally arriving with v2).

**Comment by buggy** [comment]
Hi @chloerice. I'm not talking about either of those. After a store owner installs a paid app they need to agree to a charge. For apps with multiple tiers it's common to display a price table showing the plan name, the features/limits it includes and a button to select that plan. This way the store owner can select the plan that best fits them.

There may also be a way to guide people to select a particular plan by add a label (like "Popular") or having one plan stand out visually on the page.

See the images on https://www.google.com.au/search?q=pricing+table for examples.

Given that many Shopify apps need a page like this it would be helpful if there was a component or standard example of how to implement it. That way we all have a consistent look across our pricing tables.

**Comment by ry5n** [comment]
We’ve had some discussions about this and come to the conclusion that we’d like to offer some suggestions for this in the future, but not to build any components for this case. We know it’s a clear need, but it’s also a critical page for your business, and I don’t know that we’ll ever be able to anticipate all the different ways of arranging content, number of tiers, pricing periods, etc.

Although a speeding up build time is something Polaris can do, I’d encourage app developers to spend the time to have control of the details of a pricing page so that you’re free to make tweaks.

That said, I can share an example of how we applied the [Polaris visual language](https://polaris.shopify.com/visuals/colors) to one Shopify’s features:

![image](https://user-images.githubusercontent.com/804014/40810905-1633bf46-64e4-11e8-8997-f317b4f0a2f0.png)

Again, we’d like to provide some additional examples and best practices in future, but right now that’s on our backlog. I’ll close this issue for now, but **we encourage everyone who’d like to see additional guidelines to add a 👍** to the original issue report. We’ll take it into account when we look at what to work on next.

💜

**Comment by buggy** [comment]
@ry5n Is there any chance you could share the code for that?

**Comment by ry5n** [comment]
In this case I can’t—this hasn’t been built in React. However, the pricing table part should be buildable mostly with React components (`Card`, `DisplayText`, `Button`, with `Badge` for the “Recommended” text). The custom part would be the layout for the cards (wrapping on small screen), and positioning the badge.

**Comment by MatiasFMolinari** [comment]
Is it possible to piggy-back off the pricing table that's being teased for the new app store? I've been filling up the "Enhanced listing" and the inputs seem fairly standardized.

I'm referring to this one: https://help.shopify.com/assets/api/listing-in-the-app-store/desktop-pricing-view

Not sure if React or Polaris is being used to build it, but there might be some overlap. Obviously easier said than done, but it could shave a couple of days of design work for future apps.

Also, thanks for building this amazing tool! It's saving me so much time! :heart:

**Comment by stephengardner** [comment]
A year later, this is probably still quite relevant and worth revisiting, despite being relatively easy to construct in one's own custom component structure.  +1.
