### ISSUE TITLE
Color Picker Format

### ISSUE THREAD

**Issue by robbyklein** [Shopify/polaris#267]
# Issue summary

More of a request. The ColorPicker component outputs an HSBa color object which we have to convert to a usable CSS color format. It would be so much better if it output RGBa, HSLa, hex, or all of the above like the [react-color](https://github.com/casesandberg/react-color) module does.

## Expected behavior

This framework is for building Shopify apps. `background-color: hsba()` does not exist. Make it easy for us so we don't have to use crazy conversion formulas.

## Specifications

- Polaris version: 1.10.2
- React version: 16.2.0
- Browser: Firefox 58
- Device: Macbook
- Operating System: MacOS

**Comment by meecrobe** [comment]
+1. I am building an app where I user color pickers and I have to do multiple conversions: HSBa→RGBa, HEX→HSBa, HSBa→HEX, HEX→RGBa. That's really painful :confounded:

**Comment by rkbhochalya** [comment]
Same here. I'm wondering why they designed it in a way which is not useful for most of app developers.

**Comment by lemonmade** [comment]
The picker itself is an HSBA picker. We can’t really provide a different color format without losing some granularity on the color being described. There are a number of functions Polaris exposes (see this file: https://github.com/Shopify/polaris/blob/master/src/components/ColorPicker/color-utilities.ts) which allow conversion between HSB/ RGB/ HEX. Our recommended approach is to store the HSB(A) color in state, and then use these utilities when you need to present the color in CSS/ save it as part of a form.

**Comment by ry5n** [comment]
I don't have a release timeframe, but I can share that we’re working on addressing this.

**Comment by chloerice** [comment]
Hi folks 👋 We treat all feature requests as part of our backlog, so I’ll close this issue for now. 

**we encourage everyone who wants this feature to add a 👍** to the issue's description. We take your collective interest into account when we look at what to put on the roadmap next.

💜

**Comment by pratiknikam** [comment]
@chloerice any update around this?

**Comment by chloerice** [comment]
Hey @pratiknikam, it's not on our roadmap to change the format of the color picker component at this time. Here's a [sandbox example of an rgba input](https://codesandbox.io/s/2w510vlw6n). There's [work in progress](https://github.com/Shopify/polaris-react/pull/2186) improving the design and accessibility of the color picker, but it's being worked on as time permits due to other projects the contributor is part of.

**Comment by robbyklein** [comment]
@chloerice It's really weird that this hasn't been changed yet. It's been 3 years since I created this issue. Just change it already, no one uses HBS colors. I guarantee there's hundreds of people not using this component because of the color format.

**Comment by tomoyukikashiro** [comment]
Hi folks ✋ 

I found that they export bunch of color converters such as ` hsbToRgb`.

https://github.com/Shopify/polaris-react/blob/c80d6d5082126c2e41c33bd843845998e375fb22/src/index.ts#L41-L50

**Comment by umutsesen** [comment]
Still not fixed. It has been 4 years, thanks shopify.

**Comment by nafeeur10** [comment]
```
import { useCallback, useState } from "react";
import { 
    hsbToHex,
    ColorPicker
} from "@shopify/polaris"

export default function ColorPicker() {
    const [color, setColor] = useState({
            hue: 120,
            brightness: 1,
            saturation: 1,
        });
    const handleChangeColor = useCallback((newValue) => {
        setColor(newValue)
        console.log(hsbToHex(color))
    }, [])
   return (
       <ColorPicker onChange={handleChangeColor} color={color} />
   )
}
```
I think this code could solve the problem.

**Comment by ComicDansMS** [comment]
The annoying thing is that the colour picker found in the Shopify admin is different to this one. The one in Admin has a text field containing the HEX value, and also a swatch preview of the colour.

It would be great if this was a component that we could grap from the Polaris library. Trying to write it myself and there seems to be a bit more going on to enable the user to input a HEX as well as use the colour picker.



edit: I've ended up making a colour picker that uses HEX and has a text field as well, similar to what's used in Shopify admin. The only difference is the swatch isn't half filled with the previous colour, and it also requires all 6 characters in the input because getting it to accept 3 as a shorthand without autocompleting to 6 was too much.

https://gist.github.com/ComicDansMS/02612050b5d979df9e9aea436ff16a81

**Comment by Muaz-Ul-Islam** [comment]
> ```
> import { useCallback, useState } from "react";
> import { 
>     hsbToHex,
>     ColorPicker
> } from "@shopify/polaris"
> 
> export default function ColorPicker() {
>     const [color, setColor] = useState({
>             hue: 120,
>             brightness: 1,
>             saturation: 1,
>         });
>     const handleChangeColor = useCallback((newValue) => {
>         setColor(newValue)
>         console.log(hsbToHex(color))
>     }, [])
>    return (
>        <ColorPicker onChange={handleChangeColor} color={color} />
>    )
> }
> ```
> 
> I think this code could solve the problem.

It worked for me, Thanks a lot :)
BTW, If any of you is using TypeScript, then remember to add **alpha:number** as the value on my onChange Handler is returning an object with alpha in it.

**Snippet TypeScript:**
 const [menuBgColor, setMenuBgColor] = useState<MenuBgColorProps>({
        hue: 120,
        brightness: 1,
        saturation: 1,
        alpha: 1
    });
    
    WHERE, MenuBgColorProps will be like:

    export interface MenuBgColorProps {
    hue: number,
    brightness: number,
    saturation: number,
    alpha?: number
};
