### ISSUE TITLE
Drop Zone causing console errors

### ISSUE THREAD

**Issue by Cma-Rawal** [Shopify/polaris#292]
# Issue summary
Using Drop Zone component throws below error in console:
"Cannot read property 'translate' of undefined"

App fails to load 
## Specifications

- Polaris version: 2.0.0-beta.14
- React version: 16.3.0
- Browser: Chrome
- Device: Desktop
- Operating System: Mac (10.10.5 )
<img width="1340" alt="drop zone" src="https://user-images.githubusercontent.com/37910106/38468245-d3096146-3b60-11e8-87fb-e7f026f131ff.png">

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 This repo is for reporting issues and feature requests only

**Comment by dfmcphee** [comment]
Hey @Cma-Rawal. Thanks for the issue. This looks like it is caused by your app not being wrapped in the new [Provider](https://polaris-v2.shopify.com/components/behavior/provider#navigation) component. This component is now required as of v2.

We are working on some better error messages to make this more clear in the future.

**Comment by Cma-Rawal** [comment]
Thanks for the response, adding Provider did the job.
