### ISSUE TITLE
Feature Request / Question: Chart Type

### ISSUE THREAD

**Issue by ccw0505** [Shopify/polaris#321]
Does Polaris support / plan to support following charts?
- 100% Stacked Bar Chart
- Pie chart 
- Geomap

Example - 100% Stacked Bar Chart 
![image](https://user-images.githubusercontent.com/1337797/40151069-417187e0-59b0-11e8-8526-40e5b91683a9.png)

Example - Geomap
![image](https://user-images.githubusercontent.com/1337797/40151029-ffb7050a-59af-11e8-8d2d-0a3ad3d3cf49.png)

**Comment by ry5n** [comment]
We don’t have plans to release guidelines for these chart types, but ai can ask what our specialists would recommend.

We also don’t have immediate plans to release components for data viz. There are several reasons for this, partly to do with the complexities of building them, and possible dependency on other libraries. We have used both D3 and HighCharts internally, but I’d rather not impose those dependencies, especially due to HighCharts not being an open-source license.

**Comment by ccw0505** [comment]
thx

**Comment by ry5n** [comment]
In additional to the technical details, I can offer some comments on these graph types. I should note I’m not a dataviz expert. That said, I would try other graph types before using a stacked bar chart or geomap, and I would always avoid pie charts.

There are several reasons:

- Avoid legends wherever possible, instead label items directly
- Avoid visualizations where data is represented by more than one dimension (differences in length are easier to see that differences in area; this is why pie charts are bad); for more see: https://blog.funnel.io/why-we-dont-use-pie-charts-and-some-tips-on-better-data-visualizations

Here’s an example of making a “standard” stacked bar chart much more readable, but it could be that there are better ways to visualize this data that are even better: http://austinclemens.com/blog/2016/09/14/stacked-bar-charts-often-bad-makeover-vox-com-graph/

**Comment by ccw0505** [comment]
Agree pie chart is not good for UX - and we should avoid it. Good to include this tips in polaris guide.

Thanks for other info as well. We will use the available chart type from polaris and avoid building new components first.
