### ISSUE TITLE
[Resource item] Hover state when used in card fills the corners

### ISSUE THREAD

**Issue by tmlayton** [Shopify/polaris#3416]
![hover](https://user-images.githubusercontent.com/344839/95394178-c823fc80-08b0-11eb-9cdb-9f3a73ba3524.gif)

**Comment by rosskuyper** [comment]
I've started exploring this, and the problem seems a little more expansive than the screencap shows. As far as I can see the problem was present in the old design language, but the much gentler (and nearly transparent) colour makes it far less visible. 

**1. ResourceItem bottom overflow** (as shown in the screencap in the original issue)
This is fairly easily fixable by adding `--p-border-radius-wide` border radius to the last ResourceItem. 

**2. ResourceList Header overflow**
The white background of the header also overflows the top corners. This is actually also visible in the screencap above, just a fair deal less obvious. Also fairly easy to fix by adding the border radius to `HeaderOuterWrapper` and `HeaderWrapper`.

**3. ResourceItem (without header) top overflow**
This is trickier to solve and some direction of the preferred approach would be appreciated. As you can see in the below screenshot, when there is a ResourceList without a header, the first item will need a top border radius to contain the background. 

<img width="311" alt="ResourceItem top overflow" src="https://user-images.githubusercontent.com/3041033/95783756-ca33f400-0cd2-11eb-9363-44903392cd5c.png">

Seems like there isn't a way to keep a solution nicely within just one component. The ResourceItems need to know whether the ResourceList as a whole has a header or not to be able to implement those styles. Would leveraging the existing `ResourceListContext` be the way to go here? 

An alternative approach would involve applying the border radius and catching the overflow at the ResourceList level, if adding `overflow: hidden` higher up isn't problematic, but even if that isn't now it still strikes me as far less than ideal. 

--- 

Some quick side notes

1. The white background for the header is being applied to both `HeaderOuterWrapper` and `HeaderWrapper`. Is that intentional / required? 
2. `ResourceItem.tsx` is applying `styles.newDesignLanguage` (which has the hover backgrounds etc) to both the `ListItem` and `ResourceItem` elements. Is this also intentional / required?

**Comment by peylun** [comment]
Bumping this as we are using this component to render Ad account list in Shopify Audiences.
We are using `ResourceList` without header so top `ResourceItem` overflows on the corners of the container component with border radius of 8px.

![image](https://github.com/Shopify/polaris/assets/32050553/8d3e8f53-1c8a-4ea1-aa7f-81a8e6ddc9e7)

We worked around this by setting `overflow: hidden` (with `Box`'s `overflowX` and `overflowY`) on the container component.

However, this wouldn't fix the whitespace on the last item now when scrollbar is present:

![image](https://github.com/Shopify/polaris/assets/32050553/95c19069-37f0-44f2-9325-d8833433d16a)

> An alternative approach would involve applying the border radius and catching the overflow at the ResourceList level, if adding overflow: hidden higher up isn't problematic, but even if that isn't now it still strikes me as far less than ideal.

While it is not ideal to leave to the parent component to handle the overflow, is it worth then to introduce one in `ResourceList` to do that?
