### ISSUE TITLE
Embedded app 404 when installing to Dev store 

### ISSUE THREAD

**Issue by mattxo** [Shopify/polaris#359]
# Issue summary

I've created the basic Polaris app from the docs, created a Shopify App through Shopify Partners, applied the Api Key and set the shop url in AppProvider, published it to Azure then attempted to install the app in a Development Store through Shopify Partners. This results in a 404 displayed within Shopify Admin for that Development Store.

## Expected behavior

The app should authorise, install itself into the development store and display it's UI in Shopify Admin.

## Actual behavior

When I navigate to Shopify Partners / Apps / [APP] / Test your app and click 'Install app on store'

I am redirected to the hosted code (`https://[APP].azurewebsites.net/`)

Which briefly and correctly displays the app with some Polaris components and console logs, eg.

```
[iframe Messenger]: Posting message: {"message":"Shopify.API.initialize","data":{"apiKey":"eaa[REDACTED]","shopOrigin":"https://[STORE].myshopify.com","metadata":{"interface":{"name":"@shopify/polaris","version":"2.2.0"}},"debug":true,"forceRedirect":true}} to https://[STORE].myshopify.com }

index.es.js:418 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://[STORE].myshopify.com') does not match the recipient window's origin ('https://[APP].azurewebsites.net').
```

It then redirects automatically to `https://[STORE].myshopify.com/admin/apps/eaa[REDACTED API KEY]/?hmac=9e9[REDACTED]&shop=[STORE].myshopify.com&timestamp=1529176307 ` 

Which results in a 404 page embedded within the stores Shopify Admin 

The app code is just 

```
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap/dist/css/bootstrap-theme.css';
import './index.css';
import '@shopify/polaris/styles.css';

import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter } from 'react-router-dom';
import App from './App';
import registerServiceWorker from './registerServiceWorker';

import { AppProvider } from '@shopify/polaris';

const baseUrl = document.getElementsByTagName('base')[0].getAttribute('href');
const rootElement = document.getElementById('root');

ReactDOM.render(  
  <BrowserRouter basename={baseUrl}>
        <AppProvider
            apiKey="eaa[REDACTED API KEY]"
            shopOrigin="https://[STORE].myshopify.com"
            debug={true}
            forceRedirect={false}
        >
            <App />
        </AppProvider>
  </BrowserRouter>,
  rootElement);

registerServiceWorker();

```

The HTML the component is injected to is as follows

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="theme-color" content="#000000">
    <base href="%PUBLIC_URL%/" />
    <link rel="manifest" href="%PUBLIC_URL%/manifest.json">
    <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico">
    <title>MarketplaceIntegration</title>  
</head>
<body>
    <noscript>
        You need to enable JavaScript to run this app.
    </noscript>
    <div id="root"></div>   
</body>
</html>

```
## Steps to reproduce the problem

1. Create public Shopify App in Shopify Partners and assign App URL and Whitelisted redirection URL) to `https://[APP].azurewebsites.net/`
2. Follow Polaris documentation for the app code (npm install @shopify/polaris and apply https://polaris.shopify.com/components/get-started#using-embedded-components) (using Visual Studio's ASP.NET React template)
3. Publish to Azure through Visual Studio
4. Navigate to Shopify Partners / Apps / [APP] / Test your app and click 'Install app on store'

## Specifications

- Are you using the React components? (Y):
- Polaris version number: 2.2
- Browser: Chrome 67
- Device: PC
- Operating System: Windows 10

---

**Comment by mattxo** [comment]
Hi,

So, I've figured this out. Polaris doesn't install the app! You need to do that with the OAuth callback first. Or at least, that's what worked for me.

Cheers,
Matt

**Comment by chloerice** [comment]
@mattxo That's correct. When installing your app in your dev shop for the first time, do so through the Shopify admin OAuth callback.

**Comment by Detzler** [comment]
Hey Matt,

I have the same problem. Did you figure it out? Could you help please?

**Comment by devondragon** [comment]
I am having the same issue.  I have an app that works great when standalone, but when I try to embed it I get this issue.

My understanding is that my app's main page should be unprotected, and should check to see if this store has already installed the app, and if not, should redirect to the oauth flow.  However what is happening is when I create the Appbridge app and try to call getSessionToken, it seems to be triggering a redirect to the Shopify Admin to embed the page, but since the installation isn't done, it just 404s.  I use the token to check to see if this storefront has installed my app.

Although as I type this I realize maybe I can get the info from the host value, decode it, and pass the store host back, avoiding the getSessionToken call (assuming that's where it's all going wrong for me).

More context here: https://community.shopify.com/c/shopify-apis-and-sdks/embedded-app-oauth-not-working-there-s-no-page-at-this-address/m-p/1544188

@mattxo - how did you make the OAuth flow happen, and do you get the session token first or use the host value or something else entirely?

@chloerice - any suggestions? :). 

Thanks!
