### ISSUE TITLE
Support select type filter operators for resource list component

### ISSUE THREAD

**Issue by vladucu** [Shopify/polaris#360]
# Support select type filter operators for resource list component

<img width="233" alt="screen shot 2018-06-19 at 1 47 04 am" src="https://user-images.githubusercontent.com/160955/41566125-ba18c2d2-7362-11e8-994c-15f43a7a1f0b.png">

Add support for filters that have a `select` type operator.

## Rationale

This type of filter operators is widely used in Shopify Admin and would be really handy to be supported by the resource list component implementation too, allowing for an improved UX for filtering.

**Comment by ry5n** [comment]
Yup, we’re going to need to add this to the resource list component sooner than later. I’m checking to see if this is already under way, and will leave it open until I can provide more information.

**Comment by ry5n** [comment]
We haven’t had a chance to add this yet, but it’s on our internal roadmap. Since I can’t promise a release date, I’m going to move this to a feature request issue and close it for now. However, **we encourage everyone who wants this feature to add a 👍** to the original issue report. We’ll take your collective interest into account when we look at what to work on next.

💜
