### ISSUE TITLE
Popover.Pane doesn't handle onScrolledToBottom properly

### ISSUE THREAD

**Issue by anasyusef** [Shopify/polaris#3607]
## Issue summary

[Popover.Pane](https://polaris.shopify.com/components/overlays/popover) component doesn't handle the `onScrolledToBottom` event properly on some screens.

Digging further into this problem. I noticed that [Popover.Pane](https://polaris.shopify.com/components/overlays/popover) can be composed of the Scrollable component and that component has a `handleScroll` handler where it checks if it has scrolled to the bottom (`const hasScrolledToBottom = scrollHeight - scrollTop === clientHeight;`)

This condition doesn't become true thus not triggering the event due to `scrollHeight - scrollTop` coming very close but not equal to `clientHeight`. When I tested it, `scrollHeight - scrollTop  = 295.2` and `clientHeight = 295`

## Expected behavior

<img src="https://i.ibb.co/LdhKH37/ezgif-com-gif-maker.gif" alt="ezgif-com-gif-maker" border="0">

## Actual behavior

<img src="https://i.ibb.co/6rRT181/ezgif-com-gif-maker-1.gif" alt="ezgif-com-gif-maker-1" border="0">

## Steps to reproduce the problem

The code is taken from the official Polaris example on 'Popover with lazy loaded list'
It works on certain screens. Not really sure what is the root cause.

I tried it on the following screens:

1600 x 900 (Works)
2560 x 1440 (Doesn't work)
1920 x 1080 (Doesn't work)

## Reduced test case

https://codesandbox.io/s/incsl?module=App.js

**Comment by rorz** [comment]
Looks to me like this has the same root cause as https://github.com/Shopify/polaris-react/issues/3225, and as you have identified, it seems to be coming from this line:

https://github.com/Shopify/polaris-react/blob/6e4d0682c03066674b3e7468f09201014d27e438/src/components/Scrollable/Scrollable.tsx#L163

Have tested it locally by changing the `===` to a `<=` (somewhat counter-intuitive due to the calculation being inverted) and it seems to fix it for me.

*It is worth pointing out that I could reprod this by adjusting the page-zoom on Chrome, by zooming-out, and then the `onScrolledToBottom` callback breaks.*

Will make a PR for it.

**Comment by alex-page** [comment]
@rorz @anasyusef is this still an issue? I can't replicate it with this codesandbox. https://codesandbox.io/s/floral-sun-rzebp1?file=/index.js

Feel free to reopen if it is an issue.
