### ISSUE TITLE
footer banner

### ISSUE THREAD

**Issue by huiyuhuihui** [Shopify/polaris#407]
# Feature request summary
Does Polaris have a component to implement a footer banner? Cause the current  'Banner' need to put at the top of the page.

![image](https://user-images.githubusercontent.com/40648446/44456412-04456600-a633-11e8-9e09-478e202ebaa7.png)

## Rationale

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by danrosenthal** [comment]
We don't currently have a component in Polaris for what we're calling a global ribbon. Can you describe your use-case for such a component? Understanding how it might be used could help us prioritize.

**Comment by huiyuhuihui** [comment]
use-case: we want to show trial information for our free user, eg. the remaining days of the trial. this information banner has to appear in every page, however, we think the top banner is a litter bit of bothering users, so we want to use bottom banner to achieve this function.

**Comment by huiyuhuihui** [comment]
Our apps are AfterShip and Returns Center. Nowadays, we are standalone apps , but we will become embedded one in the future. and for now, we are using Polaris as a design guideline.

**Comment by ry5n** [comment]
@huiyuhuihui I’ve logged this as a feature request. We’ll consider releasing the global ribbon as a component available for stand-alone apps. I would not recommend it for stand-alone apps, since it would have to render inside the stand-alone app’s frame.

For the moment, I’d encourage you to explore a version of this idea, but use it as an opportunity to convey more of your stand-alone app’s brand, possibly using color. 

I’ll close this issue for now, but **we encourage everyone who wants this feature to add a 👍** to the original issue report. We’ll take your collective interest into account when we look at what to work on next.

💜
