### ISSUE TITLE
Can add prop tip Popover

### ISSUE THREAD

**Issue by tranvannhat** [Shopify/polaris#447]
# Feature request summary
We have updated v1.12.1 and read change log release. Can you add prop display tip true or false for Popover. 
We think it's really necessary, because we use Polaris completely for the application. Thanks
![screen shot 2018-10-13 at 09 49 39](https://user-images.githubusercontent.com/28804941/46900545-f4792e00-cecd-11e8-94bf-7ccb911cd761.png)

**Comment by tmlayton** [comment]
@tranvannhat just to be clear do you mean the visual tip of the popover ( 💬 <-- like the tip on this icon) or do you mean a prop to display popover as a tooltip?

As of v2.12.0 we have removed the visual tip from popover entirely as seen here: https://polaris.shopify.com/components/overlays/popover

Otherwise, if you are asking for a prop to make popover behave like a tooltip, we have the tooltip component: https://polaris.shopify.com/components/overlays/tooltip

**Comment by BPScott** [comment]
hi @tranvannhat,

As Tim says we removed the visual tip from the popover in v2.12.0. So I am clear: Are you requesting a prop on the Popover component that makes the tip present like in 2.11.x?

**Comment by tranvannhat** [comment]
> hi @tranvannhat,
> 
> As Tim says we removed the visual tip from the popover in v2.12.0. So I am clear: Are you requesting a prop on the Popover component that makes the tip present like in 2.11.x?

We want has prop for hide or display tip :) 
![screen shot 2018-10-13 at 09 49 39](https://user-images.githubusercontent.com/28804941/46900536-dd3a4080-cecd-11e8-9f1b-c95c06486f72.png)

**Comment by BPScott** [comment]
The Polaris system is designed for use by Shopify and is not designed as a general-purpose design system. Thus it represents Shopify's design choices and does not offer scope for customization (this is why we don't offer the ability to customize colors for instance).

We have decided to remove the popover tip for design reasons and we want that decision to be consistent across all of Shopify. There is no value in exposing a toggle for a feature that nobody at Shopify should use if they want a consistent visual experience.

We will not add a toggle for this functionality as it does not align with our goal of having a consistent experience.
